name: Deploy to Google Cloud

on:
  push:
    branches:
      - develop
      - release

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

    - id: 'auth'
      uses: 'google-github-actions/auth@v0.4.1'
      with:
        credentials_json: ${{ secrets.CREDENTIALS_JSON }}

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 363.0.0'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: Use variables
      run: |
        echo "GITHUB_SHA : $GITHUB_SHA" # Commit hash
        echo "GITHUB_REF_NAME : $GITHUB_REF_NAME" # Branca

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: 'Deploy using gcloud CLI'
      run: |
        gcloud builds submit --tag=gcr.io/kasula/build$GITHUB_SHA --region=europe-west1
        gcloud run deploy kasula-$GITHUB_REF_NAME --image gcr.io/kasula/build$GITHUB_SHA\
          --update-secrets="DB_URL=DB_URL:latest,DB_NAME=DB_NAME:2,SECRET_KEY=SECRET_KEY:latest,\
          DB_TEST=DB_TEST:latest,EMAIL_USER=EMAIL_USER:latest,EMAIL_PASS=EMAIL_PASS:latest,\
          HOST=HOST:latest" --region=europe-west1
