byte TxPacket(byte bID, byte bParameterLength, byte bInstruction, byte Parametros[16]) {
    //...
    //Declaracion de las variables locales igual que la funcion original...
    //...
    
    char error[] = "adr. no permitida";
    if ((Parametros[0] < 6) && (bInstruction == 3)){//si se intenta escribir en una direccion <= 0x05,
        //emitir mensaje de error de direccion prohibida:
          halLcdPrintLine(error, 8, INVERT_TEXT);
          //y salir de la funcion sin mas:
          return 0;
    }
//y el resto de la funcion sigue igual...
//...
//...
}

