@startuml

title __OBSERVER's Class Diagram__\n

  package observer.weather {
    class CurrentConditionsDisplay {
    }
  }
  

  package observer.weather {
    package observer.weatherobservable {
      class CurrentConditionsDisplay {
      }
    }
  }
  

  package observer.weather {
    package observer.weatherobservable {
      interface DisplayElement {
      }
    }
  }
  

  package observer.weather {
    interface DisplayElement {
    }
  }
  

  package observer.weather {
    package observer.weatherobservable {
      class ForecastDisplay {
      }
    }
  }
  

  package observer.weather {
    class ForecastDisplay {
    }
  }
  

  package observer.weather {
    package observer.weatherobservable {
      class HeatIndexDisplay {
      }
    }
  }
  

  package observer.weather {
    class HeatIndexDisplay {
    }
  }
  

  package observer.weather {
    interface Observer {
    }
  }
  

  package observer.weather {
    package observer.weatherobservable {
      class StatisticsDisplay {
      }
    }
  }
  

  package observer.weather {
    class StatisticsDisplay {
    }
  }
  

  package observer.weather {
    interface Subject {
    }
  }
  

  package observer.weather {
    package observer.weatherobservable {
      class WeatherData {
      }
    }
  }
  

  package observer.weather {
    class WeatherData {
    }
  }
  

  package observer.weather {
    package observer.weatherobservable {
      class WeatherStation {
      }
    }
  }
  

  package observer.weather {
    class WeatherStation {
    }
  }
  

  package observer.weather {
    package observer.weatherobservable {
      class WeatherStationHeatIndex {
      }
    }
  }
  

  package observer.weather {
    class WeatherStationHeatIndex {
    }
  }
  

  CurrentConditionsDisplay -up-|> Observer
  CurrentConditionsDisplay -up-|> DisplayElement
  CurrentConditionsDisplay o-- Subject : weatherData
  CurrentConditionsDisplay -up-|> Observer
  CurrentConditionsDisplay -up-|> DisplayElement
  ForecastDisplay -up-|> Observer
  ForecastDisplay -up-|> DisplayElement
  ForecastDisplay -up-|> Observer
  ForecastDisplay -up-|> DisplayElement
  ForecastDisplay o-- WeatherData : weatherData
  HeatIndexDisplay -up-|> Observer
  HeatIndexDisplay -up-|> DisplayElement
  HeatIndexDisplay -up-|> Observer
  HeatIndexDisplay -up-|> DisplayElement
  HeatIndexDisplay o-- WeatherData : weatherData
  StatisticsDisplay -up-|> Observer
  StatisticsDisplay -up-|> DisplayElement
  StatisticsDisplay -up-|> Observer
  StatisticsDisplay -up-|> DisplayElement
  StatisticsDisplay o-- WeatherData : weatherData
  WeatherData -up-|> Observable
  WeatherData -up-|> Subject


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
