@startuml

title __WEATHER's Class Diagram__\n

  package observer.weather {
    class CurrentConditionsDisplay {
        - temperature : float
        - humidity : float
        + CurrentConditionsDisplay()
        + update()
        + display()
    }
  }
  

  package observer.weather {
    interface DisplayElement {
        {abstract} + display()
    }
  }
  

  package observer.weather {
    class ForecastDisplay {
        - currentPressure : float
        - lastPressure : float
        + ForecastDisplay()
        + update()
        + display()
    }
  }
  

  package observer.weather {
    class HeatIndexDisplay {
        ~ heatIndex : float
        + HeatIndexDisplay()
        + update()
        - computeHeatIndex()
        + display()
    }
  }
  

  package observer.weather {
    interface Observer {
        {abstract} + update()
    }
  }
  

  package observer.weather {
    class StatisticsDisplay {
        - maxTemp : float
        - minTemp : float
        - tempSum : float
        - numReadings : int
        + StatisticsDisplay()
        + update()
        + display()
    }
  }
  

  package observer.weather {
    interface Subject {
        {abstract} + registerObserver()
        {abstract} + removeObserver()
        {abstract} + notifyObservers()
    }
  }
  

  package observer.weather {
    class WeatherData {
        - observers : ArrayList
        - temperature : float
        - humidity : float
        - pressure : float
        + WeatherData()
        + registerObserver()
        + removeObserver()
        + notifyObservers()
        + measurementsChanged()
        + setMeasurements()
        + getTemperature()
        + getHumidity()
        + getPressure()
    }
  }
  

  package observer.weather {
    class WeatherStation {
        {static} + main()
    }
  }
  

  package observer.weather {
    class WeatherStationHeatIndex {
        {static} + main()
    }
  }
  

  CurrentConditionsDisplay -up-|> Observer
  CurrentConditionsDisplay -up-|> DisplayElement
  CurrentConditionsDisplay o-- Subject : weatherData
  ForecastDisplay -up-|> Observer
  ForecastDisplay -up-|> DisplayElement
  ForecastDisplay o-- WeatherData : weatherData
  HeatIndexDisplay -up-|> Observer
  HeatIndexDisplay -up-|> DisplayElement
  HeatIndexDisplay o-- WeatherData : weatherData
  StatisticsDisplay -up-|> Observer
  StatisticsDisplay -up-|> DisplayElement
  StatisticsDisplay o-- WeatherData : weatherData
  WeatherData -up-|> Subject


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
